<?php

/**
 * Implements hook_theme().
 */
function forcontu_theming_theme($existing, $type, $theme, $path) {
  return [
    'forcontu_theming_dimensions' => [
      'variables' => [
        'length' => NULL,
        'width' => NULL,
        'height' => NULL,
        'unit' => 'cm.'
      ],
      'template' => 'forcontu-theming-dimensions',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for Hook
 * 'forcontu_theming_dimensions'.
 */
function forcontu_theming_theme_suggestions_forcontu_theming_dimensions_alter(array &$suggestions, array $variables) {
  if (\Drupal::currentUser()->isAuthenticated()) {
    $suggestions[] = 'forcontu_theming_dimensions__logged_in';
  }
}