<?php

/**
 * Implements hook_preprocess_HOOK() for comment.html.twig.
 */
function forcontu_bartik_preprocess_comment(&$variables) {
  if (
    isset($variables['elements']['#comment']) &&
    $variables['elements']['#comment']->getCommentedEntity()->bundle() == 'article'
  ) {
    $variables['attributes']['class'][] = 'forcontu';
  }
}

/**
 * Implements hook_preprocess().
 */
function forcontu_bartik_preprocess(&$variables, $hook) {
  if (\Drupal::currentUser()->hasRole('administrator')) {
    $variables['twig_debug'] = \Drupal::service('twig')->isDebug();
  }
}