<?php

/**
 * @file
 * Forcontu Entities module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function forcontu_entities_node_load(array $nodes) {
  foreach ($nodes as $node) {
    if ($node->bundle() === 'article') {
      $node->setTitle(t('Article: @title', [
        '@title' => $node->label(),
      ]));
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function forcontu_entities_user_insert(EntityInterface $entity) {
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $fipsum_manager = \Drupal::service('plugin.manager.fipsum');
  $forcontu_ipsum = $fipsum_manager->createInstance('forcontu_ipsum');

  $node = $node_storage->create([
    'type' => 'page',
    'title' => $entity->getAccountName() . ' Presentation',
    'uid' => $entity->id(),
    'body' => [
      'format' => 'basic_html',
      'value' => $forcontu_ipsum->generate(600),
    ],
  ]);

  $node->save();
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function forcontu_entities_user_predelete(EntityInterface $entity) {
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');

  $nids = \Drupal::entityQuery('node')
    ->condition('uid', $entity->id())
    ->accessCheck(FALSE)
    ->execute();

  $nodes = $node_storage->loadMultiple($nids);
  
  $node_storage->delete($nodes);
}